API:
  HOST: 0.0.0.0:4518
  READ_TIMEOUT: 5s
  WRITE_TIMEOUT: 5s
  IDLE_TIMEOUT: 180s
  SHUTDOWN_TIMEOUT: 20s
  
DEBUG:
  HOST: 0.0.0.0:4519
  READ_TIMEOUT: 180s
  WRITE_TIMEOUT: 180s
  IDLE_TIMEOUT: 180s
  SHUTDOWN_TIMEOUT: 20s
MERCADO_PAGO:
  ACCESS_TOKEN: APP_USR-6365259147312383-021423-95f36ffd13b96a710dfb8411c63d5626-2140128994
MONGO:
  CONEXION: mongodb+srv://yeremi_araya:53NnNtzQOyTkTBcG@cluster0.3vtu2jv.mongodb.net/?appName=Cluster0}
RESEND:
  APIKEY: re_TsKMTPmd_PmuhhzXEtzw7CwxyypmdXpCW


